name: Auto Merge Pull Request

on:
  workflow_run:
    workflows:
      - CI Pull Request
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: >
      github.event.workflow_run.conclusion == 'success'
    runs-on: windows-latest

    steps:
      - name: Auto merge PR into develop
        shell: pwsh
        run: |
          Write-Host "CI finalizado con éxito. PR listo para merge automático."
